version: "3.9"
services:
  notebook:
    image: jupyter/datascience-notebook
    user: root
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
        - '${HOME_DIR}:/home/jovyan/work'
        - '${HOME_DIR}/notebooks/startup:/usr/local/bin/before-notebook.d/'
    ports:
      - "8888:8888"
  ps:
    image: nacharya114/pokemonshowdown
    ports:
      - "8000:8000"